/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b31d60d9-5397-473d-9512-ec53a49fd5c5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_4PTECZUVk",
    "aws_user_pools_web_client_id": "4956l34ijt5stn88s2pq3galkp",
    "oauth": {}
};


export default awsmobile;
